189 test initial state
codefordenver/encorelink pull request #193
Opened 2016-11-08 00:11 UTC by darrenrichmond

This PR closes #[insert associated issue number here]

#### What does this PR do?
Creates a basic test to ensure our initial state is what we want it to be.

#### How does this PR make you feel? [:link:](http://giphy.com/categories/emotions/)

![](put .gif link here - can be found under "advanced" on giphy)

2016-11-09 22:49 UTC, wdoug requested changes
One small request

2016-11-09 22:49 UTC, wdoug commented on package.json
> +    "immutable": "^3.8.1",
We should remove this `immutable` dependency since we aren't using it now.

2016-11-13 16:19 UTC, darrenrichmond commented on package.json
> +    "immutable": "^3.8.1",
fixed and checked into the branch. Please retest. Thanks

2016-11-15 03:14 UTC, wdoug approved these changes

2016-11-15 03:44 UTC, merged