Add react-add-to-calendar
codefordenver/encorelink pull request #341
Opened 2017-06-13 02:24 UTC by scottfirestone

Add to calendar buttons on event rows

This PR closes #334 

#### What does this PR do?
This includes "add to calendar" buttons on the musician and organizer dashboards for each event. Once clicked, the button provides links for adding the event to the user's calendar of choice.
Note 1: "REJECTED"-status events on the musician dashboard will not include this button.
Note 2: We should consider adding a similar "add to calendar" button on event detail pages. To avoid confusing UI, the status (e.g. APPROVED, REJECTED, etc.) will need to be added to the event endpoint.

#### How does this PR make you feel? [:link:](http://gph.is/1yLfi0t)

![](http://gph.is/1yLfi0t)

2017-06-13 02:40 UTC, nlkluth requested changes
This is pretty cool 👍 - just one comment on the package

2017-06-13 02:40 UTC, nlkluth commented on package.json
> +    "react-add-to-calendar": "^0.1.4",
Can you move this to `dependencies` instead of `devDependencies`?

2017-06-13 02:51 UTC, scottfirestone commented
@nlkluth Good call. I made those changes and also fixed a couple linter warnings. 

I messed up the workflow and squashed/rebased the changes, but they should now be up.

2017-06-27 01:22 UTC, nlkluth approved these changes

2017-06-27 01:23 UTC, merged